name: Next.js Build and Release

on:
  push:
    branches:
      - nextjs

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Set .env variables
        run: |
          touch .env
          echo WAKATIME_API=$WAKATIME_API >> .env
          echo MYSQL_HOST=$MYSQL_HOST >> .env
          echo MYSQL_USER=$MYSQL_USER >> .env
          echo MYSQL_PASSWORD=$MYSQL_PASSWORD >> .env
          echo MYSQL_DATABASE=$MYSQL_DATABASE >> .env
        env:
          WAKATIME_API: ${{ secrets.WAKATIME_API }}
          MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}

      - name: Set ssh certificate variable
        run: |
          touch gitauth
          echo $CERTIFICATE >> gitauth
        env:
          CERTIFICATE: ${{ secrets.CERTIFICATE }}

      - name: Connect to server netangels
        run: |
          ssh -T -i gitauth -L 3306:/run/mysqld/mysqld.sock c87074@h42.netangels.ru

      - name: Build project
        run: npm run build

      - name: Remove tokens from .env
        run: |
          rm -r .env
          touch .env
          echo WAKATIME_API="" >> .env
          echo MYSQL_HOST="" >> .env
          echo MYSQL_USER="" >> .env
          echo MYSQL_PASSWORD="" >> .env
          echo MYSQL_DATABASE="" >> .env

      - name: Remove ssh certificate
        run: |
          rm -r gitauth

      - name: Copy public folder
        run: cp -r ./public ./.next/standalone/

      - name: Copy static folder
        run: mkdir -p ./.next/standalone/.next/static && cp -r ./.next/static/* ./.next/standalone/.next/static/

      - name: Create readme.txt
        run: echo 'Hello it'\''s build https://hoprik.ru/ №${{ github.run_number }}, for start working server you need. Node js min 18v and env VARIABLES WAKATIME_API, MYSQL_HOST, MYSQL_PORT, MYSQL_USER, MYSQL_PASSWORD, MYSQL_DATABASE, HOSTNAME (optional), PORT (optional). After set you go to cmd and write command node server.js. And if you did not specify HOSTNAME and PORT, server opened in localhost:3000 Happy hacking ^_____^' > ./.next/standalone/readme.txt

      - name: Archive production artifacts (tar.gz)
        run: cd ./.next/standalone && tar -czvf ../../build-number-${{ github.run_number }}.tar.gz .

      - name: Archive production artifacts (zip)
        run: cd ./.next/standalone && zip -r ../../build-number-${{ github.run_number }}.zip .

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          tag_name: ${{ github.run_number }}
          release_name: Release №${{ github.run_number }}
          body: It's ${{ github.run_number }} build! Check commit more info =)
          draft: false
          prerelease: false

      - name: Upload Release Asset (tar.gz)
        id: upload-release-asset-tar
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build-number-${{ github.run_number }}.tar.gz
          asset_name: build-number-${{ github.run_number }}.tar.gz
          asset_content_type: application/gzip

      - name: Upload Release Asset (zip)
        id: upload-release-asset-zip
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build-number-${{ github.run_number }}.zip
          asset_name: build-number-${{ github.run_number }}.zip
          asset_content_type: application/zip